# Generated by Django 5.0.6 on 2024-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistem_perpus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahasiswa",
            name="no_antri",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
